version: '3.8'

services:
  redis:
    image: redis
    container_name: redis-cache
    command: redis-server --requirepass mypassword123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=mypassword123

volumes:
  redis_data: